### ISSUE TITLE
Alignment of text in Sponsor section

### ISSUE THREAD

**Issue by Harsh3341** [HackTheSpace/HackTheSpace#2]
### Current View
![image](https://github.com/HackTheSpace/HackTheSpace/assets/101264150/756b1e13-622b-41eb-ac45-3c39e464741e)

### Expected View
![image](https://github.com/HackTheSpace/HackTheSpace/assets/101264150/31ada807-0d8e-44ac-94b3-962c17fe4a62)

Should I change the text alignment of the sponsor

**Comment by Harsh3341** [comment]
@Vinitpal @Akash-095 can you plz check whether changing alignment is useful or not?

**Comment by Vinitpal** [comment]
yeah its useful you can change it

**Comment by Vinitpal** [comment]
> @Vinitpal @Akash-095 can you plz check whether changing alignment is useful or not?

yeah its useful you can change it
